version: "3.8"

services:
  frontend:
    container_name: cc-frontend
    restart: always
    depends_on:
      - backend
    build:
      context: ./frontend
      target: dev 
    ports:
      - 3000:3000

  backend:
    container_name: cc-backend
    restart: always
    depends_on:
      - db
    build:
      context: ./backend
      target: dev 
    ports:
      - 5003:5003

  db:
    container_name: cc-db
    restart: always
    build: ./db
    ports:
      - 3306:3306
    volumes:
      - cc-db-volume:/var/lib/mysql

volumes:
  cc-db-volume: