apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cc-frontend
  strategy: { }
  template:
    metadata:
      labels:
        app: cc-frontend
    spec:
      containers:
      - image: nickmurdock/cc-frontend:latest
        name: cc-frontend
        env:
        - name: NEXT_PUBLIC_PORT
          valueFrom:
            configMapKeyRef:
              name: cc-frontend-configmap
              key: NEXT_PUBLIC_PORT
        - name: NEXT_PUBLIC_BACKEND
          valueFrom:
            configMapKeyRef:
              name: cc-frontend-configmap
              key: NEXT_PUBLIC_BACKEND
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: cc-frontend-configmap