apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cc-backend
  strategy: { }
  template:
    metadata:
      labels:
        app: cc-backend
    spec:
      hostname: cc-backend
      containers:
      - image: nickmurdock/cc-backend:latest
        name: cc-backend
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cc-db-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cc-db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cc-db-secret
              key: MYSQL_DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: cc-backend-configmap
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: cc-backend-configmap
              key: DB_HOST
        - name: EXPIRATION_TIME
          valueFrom:
            configMapKeyRef:
              name: cc-backend-configmap
              key: EXPIRATION_TIME
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: cc-backend-configmap