apiVersion: v1
kind: Service
metadata:
  name: cc-backend-service
spec:
  selector:
    app: cc-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 32100