import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AddNote from "../components/AddNote";
import Warning from "../components/Warning";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PrivateNote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span className={"text-violet-800"}>the PrivateNote!</span>
        </h1>

        <AddNote/>
      </main>

    </div>
  )
}
